### ISSUE TITLE
win10 下 出错 

### ISSUE THREAD

**Issue by zhuewizz** [jiakeqi/douban#3]
for(var i=0;i<os.networkInterfaces().en0.length;i++){
                                    ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (G:\frontend-douban\app\tools\imgTools.js:7:41)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (G:\frontend-douban\app\spiders\climbIndex.js:3:13)
    at Module._compile (module.js:541:32)

**Comment by jiakeqi** [comment]
已经修改了获取ip的函数
````js
// 获取ip
var ifaces = os.networkInterfaces()

Object.keys(ifaces).forEach(function (ifname) {
  var alias = 0

  ifaces[ifname].forEach(function (iface) {
    if ('IPv4' !== iface.family || iface.internal !== false) {
      // skip over internal (i.e. 127.0.0.1) and non-ipv4 addresses
      return
    }

    if (alias >= 1) {
      // this single interface has multiple ipv4 addresses
      console.log(ifname + ':' + alias, iface.address)
      IPv4 = iface.address
    } else {
      // this interface has only one ipv4 adress
      console.log(ifname, iface.address)
      IPv4 = iface.address
    }
    ++alias
  })
})
````

**Comment by jiakeqi** [comment]
现在处于升级vue2.0过程中.... 有点不稳定, 预计两天内修改完毕, 我用的mac 所以没有error  最后谢谢你提的issue😜

**Comment by jiakeqi** [comment]
@zhuewizz 旁友 已经可以了
